# Generated by Django 5.2 on 2025-04-22 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='project_photos/'),
        ),
        migrations.AddField(
            model_name='project',
            name='total_votes',
            field=models.IntegerField(default=0),
        ),
    ]
