# Generated by Django 5.2 on 2025-04-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_project_feedback_type_wanted_project_tech_stack'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='guest_access_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='pricing_plan',
            field=models.CharField(choices=[('free', 'Completely Free'), ('freemium', 'Freemium (Free tier with paid options)'), ('paid', 'Paid Only')], default='free', max_length=20),
        ),
    ]
