# Generated by Django 5.2 on 2025-04-25 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_project_guest_access_info_project_pricing_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requested_count', models.PositiveIntegerField(default=1, help_text='Number of feedback slots requested')),
                ('fulfilled_count', models.PositiveIntegerField(default=0, help_text='Number of feedback slots fulfilled')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_requests', to='core.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
