# Generated by Django 5.2 on 2025-04-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='report_handled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedback',
            name='report_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='warning_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('feedback_received', 'Feedback Received'), ('feedback_liked', 'Feedback Liked'), ('report_approved', 'Report Approved'), ('report_dismissed', 'Report Dismissed'), ('feedback_reported', 'Feedback Reported'), ('user_warning', 'User Warning')], max_length=20),
        ),
    ]
