# Generated by Django 5.2 on 2025-04-27 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_feedback_report_handled_feedback_report_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='vote_type',
            field=models.CharField(choices=[('up', 'Upvote'), ('down', 'Downvote'), ('none', 'No Vote')], default='none', max_length=10),
        ),
    ]
