# Generated by Django 5.2 on 2025-04-28 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_feedback_vote_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text='CSS class for the badge icon', max_length=100)),
                ('badge_type', models.CharField(choices=[('feedback_given', 'Feedback Given'), ('feedback_liked', 'Feedback Liked'), ('projects_submitted', 'Projects Submitted')], max_length=50)),
                ('required_count', models.PositiveIntegerField(help_text='Number required to earn this badge')),
            ],
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('feedback_received', 'Feedback Received'), ('feedback_liked', 'Feedback Liked'), ('report_approved', 'Report Approved'), ('report_dismissed', 'Report Dismissed'), ('feedback_reported', 'Feedback Reported'), ('user_warning', 'User Warning'), ('badge_earned', 'Badge Earned')], max_length=20),
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_earned', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_earned'],
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
