# Generated by Django 5.2 on 2025-04-29 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_badge_alter_notification_notification_type_userbadge'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackrequest',
            name='priority',
            field=models.BooleanField(default=False, help_text='Whether this is a high priority request'),
        ),
    ]
