# Generated by Django 5.2 on 2025-04-29 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_feedbackrequest_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='feedback_type_wanted',
        ),
    ]
