# Generated by Django 5.2 on 2025-04-29 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_project_feedback_type_wanted'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackrequest',
            name='feedback_type_wanted',
            field=models.JSONField(blank=True, default=list, help_text='Feedback types wanted by the project owner', null=True),
        ),
    ]
