# Generated by Django 5.2 on 2025-04-30 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_feedbackrequest_feedback_type_wanted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackrequest',
            name='feedback_type_wanted',
        ),
    ]
