# Generated by Django 5.2 on 2025-05-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_feedbackrequest_feedback_type_wanted'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
