# Generated by Django 5.2 on 2025-05-01 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_feedbackrequest_feedback_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackrequest',
            name='feedback_type_wanted',
            field=models.JSONField(blank=True, default=list, help_text='Types of feedback wanted for this request', null=True),
        ),
    ]
