# Generated by Django 5.2 on 2025-05-01 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_feedbackrequest_feedback_type_wanted'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('helpful', '❤️ Helpful'), ('thanks', '🙏 Thanks!'), ('considering', '💡 Considering this')], max_length=20)),
                ('follow_up_note', models.TextField(blank=True, help_text='Optional note from the project owner', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='core.feedback')),
            ],
            options={
                'unique_together': {('feedback',)},
            },
        ),
    ]
