from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('waitlist/', views.waitlist_landing_page, name='waitlist'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login_view, name='login'),
    path('profile/', views.profile, name='profile'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('project/submit/', views.submit_project, name='submit_project'),
    path('project/<int:pk>/', views.project_detail, name='project_detail'),
    path('project/<int:pk>/edit/', views.update_project, name='update_project'),
    path('project/<int:pk>/delete/', views.delete_project, name='delete_project'),
    path('feedback/', views.feedback_dashboard, name='feedback_dashboard'),
    path('feedback/<int:project_id>/give/', views.give_feedback, name='give_feedback'),
    path('feedback/<int:feedback_id>/like/', views.like_feedback, name='like_feedback'),
    path('feedback/<int:feedback_id>/react/', views.react_to_feedback, name='react_to_feedback'),
    path('feedback/<int:feedback_id>/report/', views.report_feedback, name='report_feedback'),
    path('project/<int:project_id>/get-feedback/<int:credits>/', views.get_feedback, name='get_feedback'),
    path('project/<int:project_id>/request-feedback/', views.get_feedback_page, name='get_feedback_page'),
    path('project/<int:project_id>/request-feedback/submit/', views.request_feedback, name='request_feedback'),
    path('notifications/count/', views.get_notification_count, name='notification_count'),
    path('notifications/', views.user_notifications, name='user_notifications'),
    path('notification/<int:notification_id>/', views.notification_detail, name='notification_detail'),
    path('notifications/mark-all-read/', views.mark_all_notifications_read, name='mark_all_notifications_read'),
    path('top-projects/', views.top_projects, name='top_projects'),
    path('feedback/<int:project_id>/detail/<int:feedback_id>/', views.feedback_detail, name='feedback_detail'),
    path('feedback/<int:project_id>/prepare/', views.review_preparation, name='review_preparation'),
    path('about/', views.about, name='about'),
    path('privacy-policy/', views.privacy_policy, name='privacy_policy'),
    path('terms-of-service/', views.terms_of_service, name='terms_of_service'),
] 